"""add clarity tables

Revision ID: 817ad3ceb9ef
Revises: c176935a0c3a
Create Date: 2026-03-28 16:00:00.433797
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '817ad3ceb9ef'
down_revision: Union[str, None] = 'c176935a0c3a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('moby_synonyms',
    sa.Column('word', sa.Text(), nullable=False),
    sa.Column('synonyms', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('word', name=op.f('pk_moby_synonyms'))
    )
    op.create_table('phrase_map',
    sa.Column('phrase', sa.Text(), nullable=False),
    sa.Column('replacement', sa.Text(), nullable=False),
    sa.Column('clarity_score', sa.Float(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_phrase_map'))
    )
    op.create_index(op.f('ix_phrase_map_phrase'), 'phrase_map', ['phrase'], unique=True)
    op.create_table('words',
    sa.Column('word', sa.Text(), nullable=False),
    sa.Column('subtlex_freq_per_million', sa.Float(), nullable=True),
    sa.Column('subtlex_log_freq', sa.Float(), nullable=True),
    sa.Column('aoa', sa.Float(), nullable=True),
    sa.Column('concreteness', sa.Float(), nullable=True),
    sa.Column('mrc_familiarity', sa.Float(), nullable=True),
    sa.Column('cefr_level', sa.String(length=2), nullable=True),
    sa.Column('clarity_score', sa.Float(), nullable=True),
    sa.Column('tier', sa.String(length=1), nullable=True),
    sa.PrimaryKeyConstraint('word', name=op.f('pk_words'))
    )
    op.create_index(op.f('ix_words_clarity_score'), 'words', ['clarity_score'], unique=False)
    op.create_index(op.f('ix_words_tier'), 'words', ['tier'], unique=False)
    op.create_table('scan_history',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('input_text', sa.Text(), nullable=False),
    sa.Column('overall_score', sa.Float(), nullable=True),
    sa.Column('content_words', sa.Integer(), nullable=False),
    sa.Column('flagged_words', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_scan_history_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scan_history'))
    )
    op.create_index(op.f('ix_scan_history_user_id'), 'scan_history', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scan_history_user_id'), table_name='scan_history')
    op.drop_table('scan_history')
    op.drop_index(op.f('ix_words_tier'), table_name='words')
    op.drop_index(op.f('ix_words_clarity_score'), table_name='words')
    op.drop_table('words')
    op.drop_index(op.f('ix_phrase_map_phrase'), table_name='phrase_map')
    op.drop_table('phrase_map')
    op.drop_table('moby_synonyms')
    # ### end Alembic commands ###
