"""add clarity models

Revision ID: c176935a0c3a
Revises: 801b86be184b
Create Date: 2026-03-25 22:12:51.182241
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'c176935a0c3a'
down_revision: Union[str, None] = '801b86be184b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
